---
- name: install kubevirt dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-devel

- name: clone kubevirt repository
  git:
    repo: https://github.com/kubevirt/kubevirt.git
    dest: "{{ go_path }}/{{ kubevirt_dir }}"
    clone: yes

- name: copy config-local to kubevirt directory
  template:
    src: config-local.j2
    dest: "{{ go_path }}/{{ kubevirt_dir }}/hack/config-local.sh"
    mode: 0644

- name: make distclean
  make:
    chdir: "{{ go_path }}/{{ kubevirt_dir }}"
    target: distclean

- name: make binaries
  make:
    chdir: "{{ go_path }}/{{ kubevirt_dir }}"

- name: make kubevirt docker images
  make:
    chdir: "{{ go_path }}/{{ kubevirt_dir }}"
    target: docker
