namespace: "kube-system"
docker_prefix: "kubevirt"
cluster: "openshift"
action: "provision"
release_manifest_url: "https://github.com/kubevirt/kubevirt/releases/download"
kubevirt_template_dir: "{{ role_path }}/templates"
version: 0.4.1

default_vm_templates:
  - "vm-template-fedora"
  - "vm-template-windows2012r2"
  - "vm-template-rhel7"
virt_api_image_version: "{{ version }}"
virt_controller_version: "{{ version }}"
virt_handler_version: "{{ version }}"
