cdi_namespace: "{{ cdi_image_namespace | default('kube-system') }}"
cdi_storageclass: "{{ cdi_kubevirt_storageclass | default('kubevirt') }}"
apb_action: "provision"
docker_prefix: "{{ cdi_repo_tag | default('kubevirt') }}"
cdi_release_tag: "v1.3.0"
version: "1.3.0"
release_tag: "{{ cdi_release_tag }}"
docker_tag: "{{ cdi_release_tag }}"
uploadproxy_image: "{{ cdi_uploadproxy_image | default('cdi-uploadproxy') }}"
apiserver_image: "{{ cdi_apiserver_image | default('cdi-apiserver') }}"
uploadserver_image: "{{ cdi_uploadserver_image | default('cdi-uploadserver') }}"
controller_image: "{{ cdi_controller_image | default('cdi-controller') }}"
importer_image: "{{ cdi_importer_image | default('cdi-importer') }}"
cloner_image: "{{ cdi_cloner_image | default('cdi-cloner') }}"
cdi_release_manifest_url: "https://github.com/kubevirt/containerized-data-importer/releases/download"
cdi_template_dir: "{{ role_path }}/templates"
pull_policy: "{{ cdi_image_pull_policy | default('IfNotPresent') }}"
verbosity: "{{ cdi_log_verbosity | default('1') }}"
cdi_offline_template_dir: "/opt/apb/kubevirt-templates/cdi"
