# Desription: Create a virtual environment using Lago.
# The specification of the environment can be found in LagoInitFile.yaml
#
# PARAMETERS:
# inventory_file: Path to the inventory file,
# Lago will populate it with the vms details.
#
# prefix: Where to create the lago environment

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Set prefix
      set_fact:
        prefix: "{{ prefix | default('.lago') }}"
        lago_init_file: "{{ playbook_dir }}/LagoInitFile.yml"

    - name: Render LagoInitFile
      template:
        src: "{{ lago_init_file }}.j2"
        dest: "{{ lago_init_file }}"

    - name: Init Lago env
      command:
        lago init "{{ prefix }}" "{{ lago_init_file }}"
      args:
        creates: "{{ prefix }}/default/uuid"

    - name: Remove user defined settings from inventory
      blockinfile:
        path: "{{ inventory_file }}"
        marker: "# {mark} CUSTOM SETTINGS"
        state: absent

    - name: Create Ansible Hosts file from Lago env
      shell: lago --workdir "{{ prefix }}" ansible_hosts >> "{{ inventory_file }}"

    - name: Normalize inventory file
      replace:
        path: "{{ inventory_file }}"
        regexp: 'groups=(.*)'
        replace: '\1'

    - name: Refresh inventory
      meta: refresh_inventory

    - name: Start Lago env
      command: lago --workdir "{{ prefix }}" start

- hosts: all
  any_errors_fatal: True
  gather_facts: no
  tasks:
    - name: Wait for ssh
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
        delay: 10
      delegate_to: localhost
      connection: local

    - name: Set docker storage disk path
      set_fact:
        docker_dev: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_2"
        gluster_disk_idx: "{{ '4' if inventory_hostname == groups['masters'][0] else '3' }}"

    - name: Set gluster disk path
      set_fact:
        glusterfs_devices: ["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_{{ gluster_disk_idx }}"]
      when:
        - storage_role is defined
        - storage_role == 'storage-glusterfs'

- hosts: nfs
  any_errors_fatal: True
  tasks:
    - name: Mount nfs storage
      shell: |
        disk="/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3"
        mount_path="/opt"
        mkdir -p "$mount_path"
        mkfs.ext4 -F "$disk"
        echo -e "${disk}\t${mount_path}\text4\tdefaults\t0 0" >> /etc/fstab
        mount "$disk" "$mount_path"

- hosts: lago-node0
  tasks:
    - name: Mark lago-node0 as infra
      set_fact:
        openshift_node_labels:
          region: infra
          zone: default
