---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- name: Check for kubevirt.yml template in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/kubevirt.yml"
  register: byo_template

- name: Use kubevirt.yml template from {{ kubevirt_template_dir }}
  set_fact:
    manifest_version: "release"
  when: byo_template.stat.exists == True

- include_tasks: "{{ manifest_version }}.yml"

- name: Delete KubeVirt Resources
  command: "kubectl delete -f /tmp/{{ item }}.yml"
  with_items:
    - "{{ dev_template_resources }}"
  when: manifest_version=="dev"

- name: Delete KubeVirt Resources
  command: kubectl delete -f /tmp/kubevirt.yml
  when: manifest_version=="release"


- name: Delete Privileged Policy
  command: "oc adm policy remove-scc-from-user privileged -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Delete Hostmount-anyuid Policy
  command: "oc adm policy remove-scc-from-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"
