---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- name: Check for kubevirt.yml template in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/kubevirt.yml"
  register: byo_template

- name: Render BYO template
  template:
    src: "{{ kubevirt_template_dir }}/kubevirt.yml"
    dest: /tmp/kubevirt.yml
  when: byo_template.stat.exists == True

- name: Check that kubevirt.yml still exists in /tmp
  stat:
    path: "/tmp/kubevirt.yml"
  register: kubevirt_template

- name: Download KubeVirt Template
  get_url:
    url: "{{ release_manifest_url }}/{{ version }}/kubevirt.yaml"
    dest: "/tmp/kubevirt.yml"
  when: kubevirt_template.stat.exists == False

- name: Render KubeVirt Yml
  replace:
    path: "/tmp/kubevirt.yml"
    regexp: "namespace: kube-system"
    replace: "namespace: {{ namespace }}"
  when: kubevirt_template.stat.exists == False

- name: Delete KubeVirt Resources
  command: kubectl delete -f /tmp/kubevirt.yml --ignore-not-found=true

- name: Delete Privileged Policy
  command: "oc adm policy remove-scc-from-user privileged -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Delete Hostmount-anyuid Policy
  command: "oc adm policy remove-scc-from-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"
