---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"
        and admin_user is defined
        and admin_password is defined

- name: Check if {{ namespace }} exists
  shell: kubectl get ns | grep -w {{ namespace }} | awk '{ print $1 }'
  register: ns

- name: Create {{ namespace }} namespace
  shell: kubectl create namespace {{ namespace }}
  when: ns.stdout != namespace

- name: Add Privileged Policy
  command: "oc adm policy add-scc-to-user privileged -z {{ item }} -n {{ namespace }}"
  with_items:
    - kubevirt-privileged
    - kubevirt-controller
    - kubevirt-infra  # For KubeVirt v0.2.0
  when: cluster=="openshift"

- name: Add Hostmount-anyuid Policy
  command: "oc adm policy add-scc-to-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Check for kubevirt.yml template in {{ kubevirt_template_dir }}
  stat:
    path: "{{ kubevirt_template_dir }}/kubevirt.yml"
  register: byo_template

- name: Download KubeVirt Template
  get_url:
    url: "{{ release_manifest_url }}/v{{ version }}/kubevirt.yaml"
    dest: "/tmp/kubevirt.yml"
  when: byo_template.stat.exists == False

- name: Render KubeVirt Yml
  replace:
    path: "/tmp/kubevirt.yml"
    regexp: "namespace: kube-system"
    replace: "namespace: {{ namespace }}"
  when: byo_template.stat.exists == False

- name: Render BYO template
  template:
    src: "{{ kubevirt_template_dir }}/kubevirt.yml"
    dest: /tmp/kubevirt.yml
  when: byo_template.stat.exists == True

- name: Create KubeVirt Resources
  command: kubectl apply -f /tmp/kubevirt.yml

- name: Download KubeVirt source
  get_url:
    url: "https://github.com/kubevirt/kubevirt/archive/v{{ version }}.tar.gz"
    dest: "/tmp/kubevirt.tar.gz"
  when: cluster == "openshift"

- name: Extract /tmp/kubevirt.tar.gz into /tmp/kubevirt
  unarchive:
    src: "/tmp/kubevirt.tar.gz"
    dest: "/tmp/"
  when: cluster == "openshift"

- name: Create default VM templates in OpenShift Namespace
  shell: "oc create -f /tmp/kubevirt-{{ version }}/cluster/{{ item }}.yaml -n openshift"
  with_items:
    - "{{ default_vm_templates }}"
  when: cluster == "openshift"
