namespace: "kube-system"
cluster: "openshift"
apb_action: "provision"

multus_provisioner_name: "kube-multus-amd64"
multus_provisioner_repo: "docker.io/nfvpe/multus"
multus_provisioner_release: "snapshot"

cni_provisioner_repo: "quay.io/schseba/cni-plugins"
cni_provisioner_name: "kube-cni-plugins-amd64"
cni_provisioner_release: "latest"

ovs_provisioner_repo: "quay.io/kubevirt/ovs-cni-plugin"
ovs_provisioner_name: "kube-ovs-cni-plugin-amd64"
ovs_provisioner_release: "latest"

origin_node_provisioner_name: "ovs-vsctl-amd64"
origin_node_provisioner_repo: "docker.io/openshift/origin-node"
origin_node_provisioner_release: "latest"

deploy_cni_plugins: true
deploy_ovs_plugin: true

openshift_cni_config: |
  '{
    "name": "multus-cni-network",
    "type": "multus",
    "delegates": [{
      "type": "openshift-sdn",
      "name": "openshift.1",
      "masterplugin": true
    }],
    "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
  }'

kubernetes_cni_config: |
  '{
    "name": "multus-cni-network",
    "type": "multus",
    "delegates": [
     {
       "type": "weave-net",
       "name": "weave-net.1",
       "hairpinMode": true
     }
    ],
    "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
  }'
