---
kubevirt_web_ui_namespace: "kubevirt-web-ui"
openshift_console_namespace: "openshift-console"
registry_url: "quay.io"
registry_namespace: "kubevirt"

files_dir: "./roles/kubevirt_web_ui/files"
cluster_command: "oc" # in case the roles/playbook is not executed from kubevirt.yml
