apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cdi-deployment
spec:
  selector:
    matchLabels:
      app: cdi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cdi-controller
    spec:
      containers:
      - name: cdi-controller
        image: {{ repo_tag }}/import-controller:{{ release_tag }}
        imagePullPolicy: Always
        env:
          - name: OWN_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

