- hosts: localhost
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: kubevirt

- import_playbook: "{{ playbook_dir }}/storage.yml"
  when: enable_storage | bool
