---
- import_playbook: initial_configuration.yml

- name: Deploy kubevirt-ssp role
  hosts: localhost
  connection: local
  gather_facts: False
  environment:
    http_proxy: ""
  roles:
    - role: "kubevirt-ssp"
