---
- hosts: all
  connection: local
  gather_facts: False
  environment:
    http_proxy: ""
  tasks:
    - name: Identify cluster
      command: "oc get projects"
      register: result

    - name: Set cluster variable
      set_fact:
        platform: "openshift"
      when: "{{ result.rc }} == 0"

    - name: Login As Super User
      command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
      when: platform == "openshift"
            and admin_user is defined
            and admin_password is defined

- hosts: masters[0]
  connection: local
  gather_facts: False
  vars:
    network_role: network-multus
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - { role: "network-multus", when: network_role == 'network-multus'}

- hosts: masters[0]
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: kubevirt

- hosts: masters[0]
  connection: local
  gather_facts: False
  environment:
    http_proxy: ""
  roles:
    - role: "cdi"

- import_playbook: kubevirt-web-ui/config.yml
