---
- import_playbook: initial_configuration.yml

# Deploy network components
- import_playbook: network.yml

# Deploy kubevirt
- name: Deploy kubevirt role
  hosts: localhost
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: kubevirt

# Deploy kubevirt web UI
- import_playbook: kubevirt_web_ui.yml
  when: platform == "openshift"

# Deploy cdi
- import_playbook: cdi.yml

# Deploy kubevirt ssp
- import_playbook: kubevirt-ssp.yml
  when: platform == "openshift"

