---
- import_playbook: initial_configuration.yml

- hosts: nodes masters
  remote_user: root
  tasks:
    - name: remove multus config from nodes on deprovisioning
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/cni/net.d/00-multus.conf
        - /etc/cni/net.d/multus.d
      when: network_role == 'network-multus' and apb_action == 'deprovision'

    - name: make sure OVS is installed & enabled on provisioning
      block:
      - name: make sure ovs is installed
        package:
          name: openvswitch
          state: installed
      - name: enable and start OVS
        service:
          state: started
          enabled: yes
          name: openvswitch
      when: network_role == 'network-multus' and deploy_ovs_plugin and platform == "kubernetes" and apb_action == 'provision'

    - name: configure SR-IOV device plugin
      block:
        - name: Fix SELinux labels for /var/lib/kubelet/device-plugins/
          command: restorecon -Rv /var/lib/kubelet/device-plugins/
          ignore_errors: True

      when: network_role == 'network-multus' and deploy_sriov_plugin | bool and apb_action == 'provision'


- name: Deploy network roles
  hosts: localhost
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - { role: "network-multus", when: network_role == 'network-multus'}
    - { role: "skydive", when: deploy_skydive | bool }
