---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriov-nodes-config
  namespace: {{ network_namespace }}
data:
  fallback-config: |
    {
        "resourceList":
        [
            {
                "resourceName": "sriov",
                "rootDevices": [],
                "sriovMode": true,
                "deviceType": "vfio"
            }
        ]
    }
  # node01: |
  #   {
  #       "resourceList":
  #       [
  #           {
  #               "resourceName": "sriov",
  #               "rootDevices": ["02:00.0", "02:00.2"],
  #               "sriovMode": true,
  #               "deviceType": "vfio"
  #           }
  #       ]
  #   }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ cni_provisioner_name }}
  namespace: {{ network_namespace }}
  labels:
    tier: node
    app: cni-plugins
spec:
  template:
    metadata:
      labels:
        tier: node
        app: cni-plugins
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: config-container
        image: fedora:28
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        command:
        - /bin/bash
        - -c
        args:
        - |
          if [ -f /etc/sriov-nodes-config/$NODE_NAME ]; then
            config_path=/etc/sriov-nodes-config/$NODE_NAME
          else
            config_path=/etc/sriov-nodes-config/fallback-config
          fi
          cp $config_path /etc/pcidp/config.json
        volumeMounts:
        - name: etc-pcidp
          mountPath: /etc/pcidp
        - name: sriov-nodes-config
          mountPath: /etc/sriov-nodes-config
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      containers:
      - name: cni-plugins
        image: {{ cni_provisioner_repo }}:{{ cni_provisioner_release }}
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /opt/cni/bin
      volumes:
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
      - name: etc-pcidp
        hostPath:
          path: /etc/pcidp
          type: DirectoryOrCreate
      - name: sriov-nodes-config
        configMap:
          name: sriov-nodes-config
