---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ ovs_cni_daemonset_name }}
  namespace: {{ network_namespace }}
  labels:
    tier: node
    app: ovs-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: ovs-cni
    spec:
      serviceAccountName: {{ ovs_cni_marker_service_account }}
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: {{ origin_node_provisioner_container_name }}
        command:
        - /bin/bash
        - -c
        - |
          cp /usr/bin/ovs-vsctl /host/usr/bin/_ovs-vsctl
          echo '#!/usr/bin/bash
          _ovs-vsctl --db unix:///run/openvswitch/db.sock $@
          ' > /host/usr/bin/ovs-vsctl
          chmod +x /host/usr/bin/ovs-vsctl
        image: {{ origin_node_provisioner_repo }}:{{ origin_node_provisioner_release }}
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: usrbin
          mountPath: /host/usr/bin
      containers:
      - name: {{ ovs_cni_plugin_container_name }}
        image: {{ ovs_cni_plugin_provisioner_repo }}:{{ ovs_cni_plugin_provisioner_release }}
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      - name: {{ ovs_cni_marker_container_name }}
        image: {{ ovs_cni_marker_provisioner_repo }}:{{ ovs_cni_marker_provisioner_release }}
        securityContext:
          privileged: true
        args:
          - -node-name
          - $(NODE_NAME)
          - -ovs-socket
          - unix:///host/run/openvswitch/db.sock
        volumeMounts:
          - name: ovs-run
            mountPath: /host/run/openvswitch
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: usrbin
          hostPath:
            path: /usr/bin
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: ovs-run
          hostPath:
            path: /run/openvswitch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ ovs_cni_marker_cluster_role }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - get
  - update
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ ovs_cni_marker_cluster_role_binding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ ovs_cni_marker_cluster_role }}
subjects:
- kind: ServiceAccount
  name: {{ ovs_cni_marker_service_account }}
  namespace: {{ network_namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ ovs_cni_marker_service_account }}
  namespace: {{ network_namespace }}
