---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: {{ namespace }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ sriovdp_provisioner_name }}
  namespace: {{ namespace }}
  labels:
    tier: node
    app: sriovdp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: sriovdp
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: sriov-device-plugin
      containers:
      - name: kube-sriovdp
        image: {{ sriovdp_provisioner_repo }}:{{ sriovdp_provisioner_release }}
        args:
        - --log-dir=sriovdp
        - --log-level=10
        securityContext:
          privileged: false
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins/
          readOnly: false
        - name: sysfs
          mountPath: /sys
          readOnly: true
        - name: config
          mountPath: /etc/pcidp/config.json
          readOnly: true
        - name: log
          mountPath: /var/log
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins/
        - name: log
          hostPath:
            path: /var/log
        - name: sysfs
          hostPath:
            path: /sys
        - name: config
          hostPath:
            path: /etc/pcidp/config.json
