---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriov-nodes-config
  namespace: {{ network_namespace }}
data:
  fallback-config: |
    {
        "resourceList":
        [
            {
                "resourceName": "sriov",
                "rootDevices": [{{ sriov_pci_ids }}],
                "sriovMode": true,
                "deviceType": "vfio"
            }
        ]
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: {{ network_namespace }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ sriovdp_provisioner_name }}
  namespace: {{ network_namespace }}
  labels:
    tier: node
    app: sriovdp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: sriovdp
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: sriov-device-plugin
      initContainers:
      - name: config-container
        image: fedora:29
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        command:
        - /bin/bash
        - -c
        args:
        - |
          if [ -f /etc/sriov-nodes-config/$NODE_NAME ]; then
            config_path=/etc/sriov-nodes-config/$NODE_NAME
          else
            config_path=/etc/sriov-nodes-config/fallback-config
          fi
          cp $config_path /etc/pcidp/config.json
        volumeMounts:
        - name: config
          mountPath: /etc/pcidp/config.json
        - name: configmap
          mountPath: /etc/sriov-nodes-config
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      containers:
      - name: kube-sriovdp
        image: {{ sriovdp_provisioner_repo }}:{{ sriovdp_provisioner_release }}
        args:
        - --log-level=10
        securityContext:
          privileged: false
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins/
          readOnly: false
        - name: sysfs
          mountPath: /sys
          readOnly: true
        - name: config
          mountPath: /etc/pcidp/config.json
          readOnly: true
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins/
        - name: sysfs
          hostPath:
            path: /sys
        - name: config
          hostPath:
            path: /etc/pcidp/config.json
            type: FileOrCreate
        - name: configmap
          configMap:
            name: sriov-nodes-config
